---
- name: Install ganglia-monitor
  apt: name=ganglia-monitor
- name: Install ganglia-monitor-python
  apt: name=ganglia-monitor-python
- name: Configure gmond.conf 
  template: 
      src=default_gmond.conf.j2 
      dest=/etc/ganglia/gmond.conf
      mode=0644 
      owner=root 
      group=root
  notify: restart ganglia-monitor
